### ISSUE TITLE
HTTP 500 when posting form to create poll on https://quadraticvote.co/

### ISSUE THREAD

**Issue by mx00s** [Anish-Agnihotri/quadratic-voting#15]
I was excited to give the service at https://quadraticvote.co/ a try, but when I try to submit the form the Developer Tools indicate an HTTP 500 response. Also, the only sign anything is wrong in the UI is the spinner on the "Create Event" button keeps going indefinitely.

**Comment by Anish-Agnihotri** [comment]
Thanks for the report; the tool hasn't been updated in a few years, so I pushed out another deploy which should have fixed things. Should work now if you try again!
