### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by nicksellen** [Anish-Agnihotri/quadratic-voting#4]
There is no license file in this repo. Is it intended to be open source? If so, it's a good idea to put one in as early as possible, so you don't need to contact all contributors for relicensing later :)

My personal recommendation for whole applications would be AGPL (see https://choosealicense.com/licenses/agpl-3.0/).

Thanks!

**Comment by DougInAMug** [comment]
Yeah! Thanks so much for starting this @Anish-Agnihotri :) It looks like QV will be a really valuable tool for all sorts of people, and licensing this will help the spread.

**Comment by Anish-Agnihotri** [comment]
Great catch @nicksellen. I've just [licensed](https://github.com/Anish-Agnihotri/quadratic-voting/blob/master/LICENSE) the application under AGPL.

Thank you!
