### ISSUE TITLE
Results don't display all voting options

### ISSUE THREAD

**Issue by EricRoche** [Anish-Agnihotri/quadratic-voting#7]
I have a vote with over 90 options. The results screen is not displaying all of the items. Can you expand the image size or allow us to dump the results to a csv file or something? I'm trying to use this tool to help the City of Pearland, Texas prioritize it's budget requests by June 1st. Thanks!

**Comment by Anish-Agnihotri** [comment]
Sorry for delay, closing because now fixed.
