### ISSUE TITLE
Stale repository?

### ISSUE THREAD

**Issue by platocrat** [Anish-Agnihotri/quadratic-voting#8]
Hi @Anish-Agnihotri, i see that this repository hasn't been updated since December 2020.
Are you still maintaining this?

If not, do you think you would be willing to add additional maintainers to this repository?
I am looking to rely quadraticvote.co for frequent large votes for an org and would love to see this project maintained for the long-term 😃

**Comment by Anish-Agnihotri** [comment]
Not actively maintaining, but would love to open to maintainers! Will add you in ~45m (need to grab authenticator to add GitHub maintainers).
